# Server setup
server.port=${PORT:8080}

# MySQL Database configuration
# Conexión a MySQL usando variables de entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}


# Tus secretos de JWT y Mercado Pago (también como variables)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
mercadopago.access_token=${MP_TOKEN}

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Business Rules Configuration
business.schedule.open-time=10:00
business.schedule.close-time=23:00
business.whatsapp.number=${WHATSAPP_NUMBER:}

# Frontend Base URL (for MercadoPago redirects)
frontend.url=${FRONTEND_URL:http://localhost:8080}

# CORS Configuration
cors.allowed.origins=${CORS_ORIGINS:*}

# Ejecutar el script data.sql al arrancar
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true